### ISSUE TITLE
Reminder to re-implement library

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/strip-comments#10]
Just a friendly reminder that we need to update the main fCC repo to use this library instead of the current (buggy) Babel implementation.

@ojeytonwilliams What is the status of the npm publish?

**Comment by ojeytonwilliams** [comment]
Thanks for the reminder - you're right we should do this sooner rather than later. I don't think much needs doing, so I'll crack on with that tomorrow and create a PR once that's in the registry.

**Comment by ojeytonwilliams** [comment]
https://www.npmjs.com/package/@freecodecamp/strip-comments :tada:
